# Project specific config
dist: trusty

matrix:
  include:
    - os: linux
      language: python
      python: "2.7"
    - os: linux
      language: python
      python: "3.5"
      env: ATOM_CHANNEL=beta
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew list python || brew install python
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew list python || brew install python
      env: ATOM_CHANNEL=beta

install:
  - pip install pydocstyle

# Generic setup follows
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master

node_js: lts/*

after_success:
  # Add apm to the PATH
  - export PATH=${PATH}:${HOME}/atom/usr/bin/

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
