language: generic

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="atom-linter"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
