language: python

notifications:
  email:
    on_success: never
    on_failure: change

os:
  - linux

python:
  - "2.7"
  - "3.5"

git:
  depth: 10

sudo: required

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

install: "pip install pep257"

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
